image: maven:3-jdk-8

build:
  before_script:
    - "rm -rf ~/.m2/repository"
    - "mkdir -p ~/.m2"
    - "mkdir -p /cache/m2-repository"
    - "ln -s /cache/m2-repository ~/.m2/repository"
    - "chmod a+w /cache/m2-repository"
  script: "mvn clean verify -U -B"
  cache:
      paths:
      - m2-repository/
