language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
before_install: source /etc/mavenrc && sudo rm /etc/mavenrc
script: mvn -e clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
